version: 2
updates:

  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: daily
    assignees:
      - "MaFeLP"
    reviewers:
      - "MaFeLP"
    commit-message:
      prefix: "Cargo"
      include: "scope"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    assignees:
      - "MaFeLP"
    reviewers:
      - "MaFeLP"
    commit-message:
      prefix: "GitHub Actions"
      include: "scope"
